### ISSUE TITLE
How is latest_fighter_stats.csv generated?

### ISSUE THREAD

**Issue by gumshoes** [WarrierRajeev/UFC-Predictions#11]
Hi,

How is `src\app\app_data\latest_fighter_stats.csv` generated?

thanks

**Comment by gumshoes** [comment]
Seems the `preprocessing_and_fighter_data_3.ipynb` model is used to generate it but it is out of date due to ufcstats.com removing the PASS stat.

**Comment by WarrierRajeev** [comment]
I am working on some other things. Will update the notebooks soon. `src/app` is really outdated. That will be the last to be updated. `latest_fighter_stats.csv` should be replaced by `preprocessed_data.csv` which is produced by `src/createdata/preprocess.py`. A lot of things in progress atm. You can check `src/createdata/scrape_fight_data.py` to see that `PASS` was removed.

**Comment by gumshoes** [comment]
Thanks for the info and the updates.

**Comment by jjphung** [comment]
Replacing `latest_fighter_stats.csv` will be pretty tough, but I get the idea behind it. How would you extract the "latest" fighter info from `preprocessed_data.csv`? 

I can think of replacing `latest_fighter_stats.csv` with `data.csv`? Where we can sort by descending date and search by fighter name?
