### ISSUE TITLE
Errors when executing

### ISSUE THREAD

**Issue by mblevs** [WarrierRajeev/UFC-Predictions#20]
Hey @WarrierRajeev, really interesting topic and awesome approach!

I was able to successfully execute the "python -m src.create_ufc_data" command (grabbing, processing, and saving the data) a handful of times.

However, I am no getting a series of errors, starting with attribute errors and key errors as well.

Curious if something changed in the structure of the data that's being used, causing there to be errors.

**Comment by mblevs** [comment]
Update: I deleted the UFC-Predictions folder from my device, redownloaded it, and it all works properly now!

**Comment by WarrierRajeev** [comment]
If there are no issues anymore then closing this issue 👍🏻
